name: Build and Publish .aar to Maven 
on:
   push:
     branches:
       - 'master'
     tags:
        - '**'

jobs:
   publish:
       name: Build .aar, Release and Publish
       runs-on: ubuntu-latest
       steps:
         - name: Checkout code
           uses: actions/checkout@v3.0.1
           
         - name: Setup Java JDK
           uses: actions/setup-java@v3.6.0
           with:
             distribution: adopt
             java-version: 11
             cache: gradle

         - name: Cache Gradle and Gradle Wrapper
           uses: actions/cache@v3
           with:
             path: |
                ~/.gradle/caches
                ~/.gradle/wrapper
             key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}

         - name: Make gradlew executable
           run: chmod +x ./gradlew

         - name: Build Release artifact of the library
           run: ./gradlew navigator:assembleRelease --stacktrace

         - name: Upload and close staging repo on Maven
           run: ./gradlew navigator:publishReleasePublicationToSonatypeRepository --max-workers 1 closeAndReleaseSonatypeStagingRepository --stacktrace
           env:
             OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
             OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
             SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
             SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
             SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
             SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}

         - name: Create Release
           id: create_release
           uses: actions/create-release@v1
           env:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           with:
             tag_name: ${{ github.ref }}
             release_name: ${{ github.ref }}

         - name: Upload Release .aar
           id: upload_release_asset
           uses: actions/upload-release-asset@v1.0.1
           env:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           with:
             # uses output of the previous task
             upload_url: ${{ steps.create_release.outputs.upload_url }}
             asset_path: navigator/build/outputs/aar/navigator-release.aar
             asset_name: navigator-release.aar
             asset_content_type: application/zip


           
