name: Build and Publish .aar to Maven 
on:
   push:
      tags:        
        - '**'

jobs:
   publish:
       name: Build .aar, Release and Publish
       runs-on: ubuntu-latest
       steps:
         - name: Checkout code
           uses: actions/checkout@v3.0.1
           
         - name: Setup Java JDK
           uses: actions/setup-java@v3.6.0
           with:
             distribution: adopt
             java-version: 11
             cache: gradle

         - name: Cache Gradle and Gradle Wrapper
           uses: actions/cache@v3
           with:
           path: |
             ~/.gradle/caches
             ~/.gradle/wrapper
           key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}

         - name: Make gradlew executable
           run: chmod +x ./gradlew

         - name: Build Release artifact of the library
           run: ./gradlew :navigator:assembleRelease --stacktrace

         - name: Upload and close staging repo on Maven
           run: |
              ./gradlew navigator:publishReleasePublicationToSonatypeRepository 
             --max-workers 1 closeAndReleaseSonatypeStagingRepository --stacktrace
           env:
             OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
             OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
             SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
             SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
             SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
             SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}


           
