name: Build and Publish .aar to Maven 
on:
   push:
      tags:        
        - '**'
        
jobs:
   publish:
       name: release, build and publish
       runs-on: ubuntu-latest
       steps:
         - name: Checkout code
           uses: actions/checkout@v3.0.1
           
         - name: Setup Java JDK
           uses: actions/setup-java@v3.6.0
           with:
             java-version: 11
             distribution: adopt
             
         - name: Make gradlew executable
           run: chmod +x ./gradlew

         - name: build release artifact of the library
           run: ./gradlew :navigator:assembleRelease

         - name: upload and close staging repo
           run: >
             ./gradlew
             navigator:publishReleasePublicationToSonatypeRepository
             --max-workers 1
             closeAndReleaseSonatypeStagingRepository
           env:
             OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
             OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
             SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
             SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
             SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
             SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}


           
